name: Deployment

on:
  release:
    types: [released]

jobs:
  deploy:
    name: Deployment
    runs-on: self-hosted

    steps:
      - uses: TooMuch4U/runner-post-cleanup@v2.1
      
      - uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies and build
        run: |
          cd ./homepage/
          npm install
          npm run build

      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USERNAME: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          target: ${{ secrets.TARGET }}
          source: "./homepage/dist/*"
          strip_components: 2
